name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🧰 Instalar dependencias del sistema
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            libffi-dev \
            libtiff-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libmtdev-dev \
            libgl
